version: "3.8"

services:
  db:
    container_name: shareit-db
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=psw
      - POSTGRES_USER=SI
      - POSTGRES_DB=shareit

  server:
    container_name: shareit-server
    build: ./server
    ports:
      - "8080:9090"
      - "8081:8081"
    depends_on:
      - db
    environment:
        - DB_PASSWORD=psw
        - DB_USER=SI
        - DB_NAME=shareit
        - DB_HOST=db
        - DB_PORT=5432
        - SERVER_PORT=9090